### ISSUE TITLE
Bugs with doautocmd

### ISSUE THREAD

**Issue by jebaum** [inside/vim-search-pulse#12]
Found a couple bugs this morning with the doautocmd that I'll fix tonight when I get home, this is to remind me to do that / document it.

1) In older versions of vim, either `doautocmd` itself or the `<nomodeline>` option for it aren't present. make sure they are so that the plugin doesn't break in those conditions. (vim 7.3, for example, doesn't have these, and throws an error on every search).

2) If the user chooses not to do anything with the autocmds, the message `No matching autocommands` will get echoed to the commandline, this should be silenced.

**Comment by inside** [comment]
My guess for fixing these bugs:

1) Testing for `exists(':doautocmd') == 2`
2) Calling `silent doautocmd` should fix this.
