### ISSUE TITLE
Plugin breaks :cabbrev expansion

### ISSUE THREAD

**Issue by thirtythreeforty** [inside/vim-search-pulse#9]
I have a few `:cabbrev` mappings that I use frequently, like `:qq` as a shortcut for `:q!`.

With this plugin installed, abbreviations are no longer triggered with <kbd>Enter</kbd>, although <kbd>Space</kbd> will still activate them.  It looks like the plugin rebinds `<CR>` in command mode to a function that does some work then returns a string `<CR>`, which is presumably interpreted as a keystroke, although I do not know why.  However, the "keystroke" is not triggering abbreviations.

**Comment by inside** [comment]
Thanks for reporting this. I haven't found a solution yet, but still working on it! :-)

**Comment by thirtythreeforty** [comment]
Thanks for your attention!  It's not a dealbreaker by any stretch; I know from experience how easy it is to break random obscure Vim features when you change any behavior.

**Comment by inside** [comment]
I just pushed the fix in the master branch. You can update the plugin and should no longer have the issue. [See this commit for an explanation](https://github.com/inside/vim-search-pulse/commit/b1496012a2fa617ea76444c09e29aff27061f1c6).

Funny thing, I also have some command line abbreviations but always used <kbd>space</kbd> to expand them. I was never worried about triggering them with the <kbd>enter</kbd> key.

Regards,
Yann

**Comment by thirtythreeforty** [comment]
Awesome, thank you!

**Comment by inside** [comment]
You're welcome :-)
